### ISSUE TITLE
Removing CSS properties and pixel fallbacks generated by pixrem

### ISSUE THREAD

**Issue by aaronbushnell** [jonathanepollack/gulp-minify-css#46]
gulp-minify-css is removing pixel fallbacks for various CSS properties generated by pixrem. Here's my `styles.styl`:

```css
body {
  padding: 3rem 0;
  font-size: 3rem;
}
```

If I don't use gulp-minify-css, my output is:

```css
body {
  padding: 48px 0;
  padding: 3rem 0;
  font-size: 48px;
  font-size: 3rem;
}
```

When I use gulp-minify-css, the pixel fallback for `padding` gets removed and my output is:

```css
body{padding:3rem 0;font-size:48px;font-size:3rem}
```

===

My `gulpfile.js`:

```js
var gulp = require('gulp'),
    stylus = require('gulp-stylus'),
    pixrem = require('gulp-pixrem'),
    prefix = require('gulp-autoprefixer'),
    minifyCSS = require('gulp-minify-css'),
    globals = require('../globals');

gulp.task('styles', function () {
  gulp.src(globals.appPath + '/assets/stylesheets/*.styl')
    .pipe(stylus())
    .pipe(prefix())
    .pipe(pixrem())
    .pipe(minifyCSS())
    .pipe(gulp.dest(globals.appPath + '/_tmp/stylesheets'));
});
```

My `package.json`:

```json
{
  "name": "my-site",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "gulp": "^3.8.6",
    "gulp-autoprefixer": "0.0.8",
    "gulp-minify-css": "^0.3.11",
    "gulp-pixrem": "^0.1.1",
    "gulp-stylus": "^1.3.3",
  }
}
```
