### ISSUE TITLE
*:before and *:after not writing

### ISSUE THREAD

**Issue by erkanunluturk** [jonathanepollack/gulp-minify-css#82]
## *:before and *:after not writing

```javascript
keepBreaks: true,
restructuring: false
```
```stylus
*
  &
  &:before
  &:after
    box-sizing border-box
```

```css
*,:after,:before{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}
```
