### ISSUE TITLE
keepSpecialComments: 1 fails when using gulp-sourcemaps

### ISSUE THREAD

**Issue by AlexanderOMara** [jonathanepollack/gulp-minify-css#90]
This is probably an edge-case issue, but when using [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps) the option `keepSpecialComments: 1` fails to behave as expected, and instead it behaves the same as the default `keepSpecialComments: '*'`.

Here is a reproducible test case:

**test.css**
```css
/*!
comment 1
*/
a {
	color: blue;
}

/*!
comment 2
*/
b {
	color: red;
}

/*!
comment 3
*/
i {
	color: green;
}
```

**gulpfile.js**
```js
var gulp = require('gulp');
var gulpSourcemaps = require('gulp-sourcemaps');
var gulpMinifyCSS = require('gulp-minify-css');

gulp.task('css', function() {
	return gulp.src('./test.css')
		.pipe(gulpMinifyCSS({
			keepBreaks: true,
			keepSpecialComments: 1
		}))
		.pipe(gulp.dest('./min/'));
});

gulp.task('cssmap', function() {
	return gulp.src('./test.css')
		.pipe(gulpSourcemaps.init())
		.pipe(gulpMinifyCSS({
			keepBreaks: true,
			keepSpecialComments: 1
		}))
		.pipe(gulpSourcemaps.write('.', {sourceRoot: '.'}))
		.pipe(gulp.dest('./min/'));
});
```

`$ gulp css` result `min/test.css`:
```css
/*!
comment 1
*/
a{color:#00f}
b{color:red}
i{color:green}
```
(works as expected)

`$ gulp cssmap` result `min/test.css`:
```css
/*!
comment 1
*/

a{color:#00f}
/*!
comment 2
*/

b{color:red}
/*!
comment 3
*/

i{color:green}
/*# sourceMappingURL=test.css.map */
```

As you can see, the output when using gulp-sourcemaps contains too many comments.
